FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# vuex-monstro

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/paragraph]

### Paragraph [GET]

+ Response 200 (application/json)

            {
                "paragraph": "Favourite programming language?"
            }
        

## Questions Collection [/title]

### Title [GET]

+ Response 200 (application/json)

            {
                "title": "Title Legal"
            }