version: '3'
services:
  vuex-monstro:
    image: node:10-slim
    container_name: vuex-monstro
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm run serve'
    ports:
      - "8080:8080"
    # environment:
    #   - VUE_APP_API=https://nfe.backend:8443 # endereço do backend nfe.
    #   - VUE_APP_AUTH_JWT=http://localhost
